---
- name: Deploy a Web Application
  hosts: db_and_web_server
  vars_files:
   - vars/git_info.yml
  tasks:
    - name: Install all required dependencies
      apt: name={{ item }} state=installed
      with_items:
        - python
        - python-setuptools
        - python-dev
        - build-essential
        - python-pip
        - python-mysqldb
        - git

    - include: tasks/deploy_db.yml
    - include: tasks/deploy_web.yml
